services:
  nginx:
    container_name: "nginx-${AppName}"
    build:
      context: ./infra/nginx
    ports:
      - "8080:80"
    volumes:
     - ./src/:/var/www/public/
  app:
    container_name: "app-${AppName}"
    image: php:8-fpm
    volumes:
      - ./src/:/var/www/public/